#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# First-experiment PUBLICATION run orchestration for Hugging Face Jobs.
#
# Consumes the ALREADY-BUILT verifiable model/eval package produced by
# tools/jobs/eval_run.sh (uploaded under <RUN_NAME>/eval in a runs repo) plus
# the dataset package produced by tools/jobs/proof_run.sh (under
# <RUN_NAME>/dataset), and produces + PUBLISHES the full PROOF release binder:
#
#   1. DEMO   - a terminal-inference demo package built from a LIVE
#               geno-lewm-score run against the downloaded eval package and the
#               Carbon-500M encoder mounted at /carbon.
#   2. PAPER  - paper.md generated by tools.release.paper_draft and verified
#               byte-exact by tools.release.paper_package.
#   3. PUBLISH- model + dataset uploaded to the Hugging Face Hub, demo + paper
#               uploaded to a GitHub release, via tools.release.hub_publish,
#               which then regenerates the release-candidate report and HTTP-
#               probes the live public artifacts.
#   4. BINDER - tools.release.clean_machine_demo downloads the now-public
#               artifacts and re-runs scoring on a clean machine, then
#               tools.release.publication_report binds plan + candidate +
#               publish report + clean-machine replay into
#               publication_evidence_report.json (ok=true).
#
# HONEST CLAIM BOUNDARY: this is a PROOF-scale release whose held-out ClinVar
# chr21 AUROC is ~0.52 (0.519249), i.e. statistically near chance. The paper and
# model card carry that number verbatim (it flows eval_metrics.json ->
# eval_report.md -> paper). Nothing in this script inflates or hides it; the
# release tooling refuses placeholder/fixture wording, so the published binder
# is an honest negative/near-chance result, not a performance claim.
#
# Run inside a Job from a fresh clone of the repo:
#   git clone --depth 1 https://github.com/AbdelStark/GenoLeWM /repo
#   cd /repo && pip install -e ".[train]" && pip install pyarrow
#   hf jobs run --flavor cpu-upgrade \
#     -v hf://HuggingFaceBio/Carbon-500M:/carbon \
#     -s HF_TOKEN -e GH_TOKEN=... \
#     bash tools/jobs/publish_run.sh
#
# Carbon-500M MUST be mounted read-only at $CARBON_DIR (default /carbon) because
# both the DEMO (step 2) and the clean-machine replay (step 6) build a
# CarbonStateEncoder offline (local_files_only=True) from the model package's
# training_config.yaml, whose encoder.model_id is already '/carbon'
# (geno_lewm/deploy/runtime.py:594-608; verified in the package config + manifest).
#
# ---------------------------------------------------------------------------
# WHY THE STEP ORDER IS WHAT IT IS (verified against the code):
#
#  * verify_package (invoked inside hub_release/release_candidate/hub_publish)
#    requires THREE directories: a model-dir, a full dataset PACKAGE dir, and a
#    terminal DEMO dir (tools/release/paper_package.py:_verify_dataset_dir /
#    _verify_demo_dir). The downloaded eval package is ONLY the model-dir; its
#    inner eval/dataset_manifest.json is a 97-byte eval-input stub, NOT a
#    publishable dataset package. So the dataset dir is downloaded separately and
#    the demo dir is built here from the model dir.
#
#  * The DEMO must RUN the model: tools.demo.terminal_inference shells out to
#    `geno-lewm-score` (terminal_inference.py:104-126,393-399) and writes its OWN
#    fresh scores.jsonl/receipts.jsonl + runtime_preflight_report.json +
#    batch_receipt_report.json + terminal-demo-transcript.md +
#    terminal_demo_manifest.json into --output-dir. The package's existing
#    eval/scores.jsonl (the ClinVar AUROC scores) is UNRELATED and must not be
#    reused. The --vcf and --fasta MUST live physically inside --output-dir or
#    paper_draft._verified_demo_vcf_summary and hub_release._ensure_under_root
#    reject them as 'outside_package' (terminal_inference.py:321-323;
#    paper_draft.py:578; hub_release.py:421). We therefore stage the demo VCF +
#    FASTA into the demo dir before running.
#
#  * The demo refuses fixture/dummy/test manifests by default; the real ids
#    (release_id=geno-lewm-v0.1.0-r1, snapshot=geno-lewm-data-v0.1.0-r1) pass the
#    gate (terminal_inference.py:415-435), so we do NOT pass
#    --allow-fixture-manifest. We also do NOT pass --no-require-native-runtime:
#    the preflight requires torch/safetensors.torch/transformers/pyarrow.
#
#  * PAPER text is derived from real artifacts: paper_draft splices the eval
#    report's Results/Conclusions/Negative Findings/Limitations sections (which
#    are the byte-exact render of eval_metrics.json) into the paper
#    (paper_draft.py:210-213,416-425). It rejects placeholder wording unless
#    --allow-placeholders; we do NOT pass it. paper_package then re-renders the
#    paper and requires it byte-identical (paper_package.py:3066-3109), so the
#    paper is generated and verified against the SAME three dirs.
#
#  * PUBLISH-then-VERIFY: a real release_candidate (require_public_links=True,
#    the only non-fixture mode) HTTP-probes the model/dataset/demo/paper URLs and
#    byte-hashes the public files (release_candidate.py:471-539). They must be
#    LIVE first. That is why hub_publish UPLOADS (huggingface-cli upload + gh
#    release upload) and THEN regenerates the candidate (hub_publish.py:117-134).
#    The candidate re-check is mandatory and unskippable on hub_publish.
#
#  * CHAIN OF CUSTODY: the binder requires the SAME release_candidate_report.json
#    bytes to be (a) embedded in hub_publish_report.json, (b) hashed by
#    clean_machine_demo, and (c) re-hashed by publication_report
#    (publication_report.py:305-344,1260-1327). So we feed clean_machine and the
#    binder the EXACT file hub_publish wrote (--candidate-output) and never
#    re-run release_candidate separately.
#
#  * hub_publish hardcodes the legacy `huggingface-cli` binary, NOT `hf`
#    (hub_publish.py:298). We ensure it is on PATH (shim to `hf` if needed) or
#    every model/dataset upload fails with ResourceError 'release publication
#    command was not found' (hub_publish.py:401-405).
#
#  * GitHub is ALWAYS required: the demo upload command is unconditional
#    (hub_publish.py:258-280) and clean_machine fetches the demo asset from
#    api.github.com, so GH_TOKEN/GITHUB_TOKEN is mandatory even though the task
#    only guarantees HF_TOKEN. The GitHub release TAG must already exist
#    (`gh release upload` does not create it); HF model/dataset repos auto-create
#    on upload.
# ---------------------------------------------------------------------------
set -euo pipefail

# --- inputs / knobs -------------------------------------------------------
WORK="${WORK:-/tmp/geno-publish}"
OUT="${OUT:-$WORK/out}"
CARBON_DIR="${CARBON_DIR:-/carbon}"

# Runs repo + subpaths produced by the earlier stages.
RUNS_REPO="${RUNS_REPO:-abdelstark/geno-lewm-runs}"
RUN_NAME="${RUN_NAME:-geno-lewm-proof}"
EVAL_SUBPATH="${EVAL_SUBPATH:-$RUN_NAME/eval}"        # the built model/eval package
DATASET_SUBPATH="${DATASET_SUBPATH:-$RUN_NAME/dataset}"  # the dataset PACKAGE dir

# Public release targets. Model + dataset publish to the Hugging Face Hub; demo +
# paper publish to a GitHub release. The HF repos auto-create on upload; the
# GitHub release TAG must pre-exist (created below if GH_REPO is writable).
REPO_ID="${REPO_ID:-abdelstark/geno-lewm}"
DATASET_REPO="${DATASET_REPO:-abdelstark/geno-lewm-data}"
DATASET_URL="${DATASET_URL:-https://huggingface.co/datasets/${DATASET_REPO}}"
GH_REPO="${GH_REPO:-AbdelStark/GenoLeWM}"
GH_TAG="${GH_TAG:-geno-lewm-v0.1.0-r1}"
DEMO_URL="${DEMO_URL:-https://github.com/${GH_REPO}/releases/tag/${GH_TAG}}"
PAPER_FILENAME="${PAPER_FILENAME:-paper.md}"
PAPER_URL="${PAPER_URL:-https://github.com/${GH_REPO}/releases/download/${GH_TAG}/${PAPER_FILENAME}}"
PAPER_TITLE="${PAPER_TITLE:-GenoLeWM First Experiment Report}"
COMMIT_SHA="${COMMIT_SHA:-$(git rev-parse HEAD 2>/dev/null || echo 0000000)}"

# Demo input knobs. The demo scores a SMALL chr21 SNV VCF (every REF must match
# the FASTA base at that POS or score.py aborts the whole VCF; we generate the
# VCF from ClinVar via tools.data.clinvar_eval_set --fasta, which drops any row
# whose REF disagrees with the FASTA so the pass cannot abort).
EVAL_CHROM="${EVAL_CHROM:-21}"
DEMO_MAX_VARIANTS="${DEMO_MAX_VARIANTS:-32}"
# MUST match the WINDOW_BP used by proof_run.sh / eval_run.sh so the scored
# window latents match what the predictor was trained on.
WINDOW_BP="${WINDOW_BP:-4096}"
CLINVAR_URL="${CLINVAR_URL:-https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz}"
# Ensembl per-chromosome GRCh38 FASTA. File MUST end in .gz (literal suffix
# check in the scorer; .bgz would NOT be gz-decoded).
FASTA_URL="${FASTA_URL:-https://ftp.ensembl.org/pub/release-110/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.21.fa.gz}"

# Whether to upload the binder artifacts back to the runs repo at the end.
UPLOAD_BINDER="${UPLOAD_BINDER:-1}"
BINDER_UPLOAD_SUBPATH="${BINDER_UPLOAD_SUBPATH:-$RUN_NAME/publication}"

log()  { echo "=== $* ==="; }
fail() { echo "FATAL: $*" >&2; exit 1; }

# --- 0. environment preflight ---------------------------------------------
log "publish run: $RUN_NAME  repo=$REPO_ID dataset=$DATASET_URL demo=$DEMO_URL"
log "HONEST: PROOF-scale release; held-out ClinVar chr21 AUROC ~0.52 (near chance)"

[ -n "${HF_TOKEN:-}" ] || fail "HF_TOKEN is required (model + dataset publish to the Hugging Face Hub)"
# GitHub is ALWAYS required: the demo upload command is unconditional and the
# clean-machine replay fetches the demo asset from api.github.com.
if [ -z "${GH_TOKEN:-}" ] && [ -z "${GITHUB_TOKEN:-}" ]; then
  fail "GH_TOKEN or GITHUB_TOKEN is required (demo + paper publish to a GitHub release)"
fi
export GH_TOKEN="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
export HF_TOKEN

test -d "$CARBON_DIR" || fail "Carbon-500M not mounted at $CARBON_DIR (-v hf://HuggingFaceBio/Carbon-500M:/carbon)"
python -c "import torch; print('torch', torch.__version__, 'cuda', torch.cuda.is_available())" || true
python -c "import safetensors.torch, transformers, pyarrow.parquet" \
  || fail "native runtime deps missing (need torch + safetensors + transformers + pyarrow); pip install -e '.[train]' && pip install pyarrow"

# hub_publish.py hardcodes the legacy `huggingface-cli` binary (not `hf`); ensure
# it is on PATH or shim it to `hf` so the credentialed uploads can run.
if ! command -v huggingface-cli >/dev/null 2>&1; then
  if command -v hf >/dev/null 2>&1; then
    log "huggingface-cli shim -> hf (hub_publish hardcodes the legacy binary name)"
    SHIM_DIR="$WORK/bin"; mkdir -p "$SHIM_DIR"
    printf '#!/usr/bin/env bash\nexec hf "$@"\n' > "$SHIM_DIR/huggingface-cli"
    chmod +x "$SHIM_DIR/huggingface-cli"
    export PATH="$SHIM_DIR:$PATH"
  else
    fail "neither 'huggingface-cli' nor 'hf' on PATH; pip install -U 'huggingface_hub[cli]'"
  fi
fi
command -v gh >/dev/null 2>&1 || fail "'gh' (GitHub CLI) not on PATH; required for demo + paper release upload"

mkdir -p "$WORK" "$OUT"
MODEL_DIR="$WORK/model"        # downloaded model/eval package (the model-dir)
DATASET_DIR="$WORK/dataset"    # downloaded full dataset PACKAGE dir
DEMO_DIR="$WORK/demo"          # built here from the model dir + a live score run
PAPER_PATH="$OUT/$PAPER_FILENAME"
INPUTS="$WORK/inputs"
mkdir -p "$MODEL_DIR" "$DATASET_DIR" "$DEMO_DIR" "$INPUTS"

# --- 1. download the built model/eval package + dataset package -----------
log "download model/eval package from $RUNS_REPO ($EVAL_SUBPATH)"
hf download "$RUNS_REPO" --repo-type model --include "$EVAL_SUBPATH/*" --local-dir "$WORK/dl-model" \
  || fail "could not download $EVAL_SUBPATH from $RUNS_REPO"
cp -a "$WORK/dl-model/$EVAL_SUBPATH/." "$MODEL_DIR/"
for f in manifest.json model_package.json model_card.md SHA256SUMS eval_metrics.json \
         eval_config.effective.yaml eval_report.md efficiency_report.json training_config.yaml \
         predictor.safetensors action_encoder.safetensors calibration.parquet \
         training_run_manifest.json training_run_card.md training_run_SHA256SUMS \
         training_preflight_report.json; do
  test -s "$MODEL_DIR/$f" || fail "model package missing required file: $f"
done
# The committed config must already point encoder.model_id at the Carbon mount.
python - "$MODEL_DIR" "$CARBON_DIR" <<'PY' || fail "model package training_config.yaml encoder.model_id is not the Carbon mount path"
import sys, yaml
cfg = yaml.safe_load(open(f"{sys.argv[1]}/training_config.yaml"))
mid = (cfg.get("encoder") or {}).get("model_id")
assert mid == sys.argv[2], f"encoder.model_id={mid!r} (expected {sys.argv[2]!r}); demo would not load Carbon offline"
print("encoder.model_id =", mid)
PY

log "download dataset package from $RUNS_REPO ($DATASET_SUBPATH)"
hf download "$RUNS_REPO" --repo-type model --include "$DATASET_SUBPATH/*" --local-dir "$WORK/dl-dataset" \
  || fail "could not download dataset package $DATASET_SUBPATH from $RUNS_REPO (build it with tools.release.dataset_snapshot in the proof stage)"
cp -a "$WORK/dl-dataset/$DATASET_SUBPATH/." "$DATASET_DIR/"
for f in dataset_manifest.json dataset_package.json data_card.md SHA256SUMS \
         dataset_snapshot_report.json dataset_input_check_report.json; do
  test -s "$DATASET_DIR/$f" || fail "dataset package missing required file: $f (not a publishable dataset dir)"
done

# --- 2. build the DEMO dir from a LIVE geno-lewm-score run ----------------
# Stage a small chr21 SNV VCF + the chr21 FASTA INSIDE the demo dir, then run the
# terminal demo with --output-dir == the demo dir. clinvar_eval_set --fasta drops
# any row whose REF disagrees with the FASTA so the score pass cannot abort.
log "stage chr$EVAL_CHROM FASTA + a small demo VCF INSIDE the demo dir"
DEMO_FASTA="$DEMO_DIR/chr${EVAL_CHROM}.fa.gz"   # FASTA physically inside demo dir
DEMO_VCF="$DEMO_DIR/demo.vcf"                    # VCF physically inside demo dir
CLINVAR_FULL="$INPUTS/clinvar.GRCh38.vcf.gz"
CLINVAR_CHR="$INPUTS/clinvar.chr${EVAL_CHROM}.vcf.gz"
DEMO_LABELS="$INPUTS/demo.labels.jsonl"         # discarded; only the VCF is used

curl -fsSL "$CLINVAR_URL" -o "$CLINVAR_FULL" || fail "ClinVar download failed"
curl -fsSL "$FASTA_URL"  -o "$DEMO_FASTA"      || fail "FASTA download failed"
echo "FASTA header: $(zcat "$DEMO_FASTA" 2>/dev/null | head -1)"

# Line-level prefilter to the eval chromosome (full ClinVar is ~3M rows).
zcat "$CLINVAR_FULL" 2>/dev/null \
  | awk -F'\t' -v c="$EVAL_CHROM" '/^#/ || ($1 == c || $1 == "chr" c)' \
  | gzip > "$CLINVAR_CHR"
test -s "$CLINVAR_CHR" || fail "chr$EVAL_CHROM ClinVar subset is empty"

python -m tools.data.clinvar_eval_set \
  --input-vcf "$CLINVAR_CHR" --chrom "$EVAL_CHROM" --fasta "$DEMO_FASTA" \
  --max-variants "$DEMO_MAX_VARIANTS" \
  --labels-out "$DEMO_LABELS" --vcf-out "$DEMO_VCF" \
  || fail "could not build a scoreable demo VCF"
test -s "$DEMO_VCF" || fail "demo VCF is empty"
# Demo VCF must contain >=1 scoreable record or summarize_vcf_input aborts.
grep -qv '^#' "$DEMO_VCF" || fail "demo VCF has no variant records"
echo "demo VCF: $(grep -cv '^#' "$DEMO_VCF") scoreable variants"

log "run terminal demo (LIVE geno-lewm-score; writes 6 artifacts into $DEMO_DIR)"
# HF_HUB_OFFLINE=1: the score subprocess loads Carbon offline from /carbon.
# Do NOT pass --allow-fixture-manifest (real ids pass) nor --no-require-native-
# runtime (deps verified above). --carbon-cache-dir makes the carbon evidence
# explicit; omit --require-carbon-cache (the mount layout may not match the
# cache-marker check, and the demo run is the authoritative carbon check anyway).
HF_HUB_OFFLINE=1 python -m tools.demo.terminal_inference \
  --model-dir "$MODEL_DIR" \
  --vcf "$DEMO_VCF" \
  --fasta "$DEMO_FASTA" \
  --output-dir "$DEMO_DIR" \
  --backend auto --batch-size 64 \
  --carbon-cache-dir "$CARBON_DIR" \
  || fail "terminal demo failed (most likely Carbon not loadable from $CARBON_DIR, or a REF/contig mismatch)"

for f in scores.jsonl receipts.jsonl runtime_preflight_report.json \
         batch_receipt_report.json terminal-demo-transcript.md terminal_demo_manifest.json; do
  test -s "$DEMO_DIR/$f" || fail "demo is missing $f"
done
python - "$DEMO_DIR" <<'PY' || fail "demo manifest status is not 'passed'"
import json, sys
m = json.load(open(f"{sys.argv[1]}/terminal_demo_manifest.json"))
assert m.get("status") == "passed", m.get("status")
print("demo status:", m["status"])
PY
# The demo VCF + FASTA are now load-bearing inputs that paper_draft and
# hub_release re-hash; DO NOT mutate them after this point.

# --- 3. generate the PAPER ------------------------------------------------
# AUROC ~0.52 flows eval_metrics.json -> eval_report.md sections -> paper. No
# --allow-placeholders for a real release; text derives from real artifacts.
log "generate paper draft (honest near-chance AUROC from the eval report)"
python -m tools.release.paper_draft \
  --model-dir "$MODEL_DIR" \
  --dataset-dir "$DATASET_DIR" \
  --demo-dir "$DEMO_DIR" \
  --output "$PAPER_PATH" \
  --title "$PAPER_TITLE" \
  || fail "paper_draft failed (check eval_report.md has Results/Conclusions/Negative Findings/Limitations and no placeholder wording)"
test -s "$PAPER_PATH" || fail "paper.md is empty"

# --- 4. VERIFY the paper + packages (gate; exit 2 on verification failure) -
# paper_package re-renders the paper from the SAME three dirs and requires it
# byte-identical, plus verifies the model/dataset/demo SHA256SUMS. Run it as the
# pre-publish gate. No --allow-fixture-manifest for a real release.
log "verify package + paper (paper_package; byte-exact paper re-render)"
python -m tools.release.paper_package \
  --model-dir "$MODEL_DIR" \
  --dataset-dir "$DATASET_DIR" \
  --demo-dir "$DEMO_DIR" \
  --paper-path "$PAPER_PATH" \
  || fail "paper_package verification failed (exit !=0). If 'paper.stale', re-run paper_draft against these EXACT dirs; do not hand-edit paper.md"

# --- 5. ensure the GitHub release tag exists (gh upload does NOT create it) -
# HF model/dataset repos auto-create on upload; the GitHub release tag must
# pre-exist for the demo + paper asset uploads. Create it idempotently.
log "ensure GitHub release tag exists: $GH_REPO @ $GH_TAG"
if ! gh release view "$GH_TAG" --repo "$GH_REPO" >/dev/null 2>&1; then
  gh release create "$GH_TAG" --repo "$GH_REPO" \
    --title "GenoLeWM $GH_TAG (proof; ClinVar chr21 AUROC ~0.52)" \
    --notes "Proof-scale GenoLeWM release. Held-out ClinVar chr21 rank-based AUROC ~0.52 (near chance). Demo + paper assets attached; model + dataset on the Hugging Face Hub." \
    || fail "could not create GitHub release tag $GH_TAG on $GH_REPO (need write access + GH_TOKEN)"
else
  echo "release tag $GH_TAG already exists"
fi

# --- 6. PUBLISH: upload model+dataset (HF) + demo+paper (GitHub), then -----
# regenerate the release candidate and re-probe the live public artifacts.
log "publish to the Hub + GitHub, then re-verify public readiness (hub_publish)"
PLAN_OUT="$OUT/hub_release_plan.json"
CANDIDATE_OUT="$OUT/release_candidate_report.json"
PUBLISH_OUT="$OUT/hub_publish_report.json"
python -m tools.release.hub_publish \
  --model-dir "$MODEL_DIR" \
  --dataset-dir "$DATASET_DIR" \
  --demo-dir "$DEMO_DIR" \
  --paper-path "$PAPER_PATH" \
  --repo-id "$REPO_ID" \
  --dataset-url "$DATASET_URL" \
  --demo-url "$DEMO_URL" \
  --paper-url "$PAPER_URL" \
  --commit-sha "$COMMIT_SHA" \
  --plan-output "$PLAN_OUT" \
  --candidate-output "$CANDIDATE_OUT" \
  --publish-output "$PUBLISH_OUT" \
  --public-link-timeout 60 \
  || fail "hub_publish failed: uploads may have run but the final candidate was not ready (public links/artifacts did not resolve byte-exact). Inspect $PUBLISH_OUT and $CANDIDATE_OUT; retry after Hub/GitHub propagation"
test -s "$CANDIDATE_OUT" || fail "hub_publish did not write $CANDIDATE_OUT"
test -s "$PUBLISH_OUT"   || fail "hub_publish did not write $PUBLISH_OUT"

# --- 7. CLEAN-MACHINE replay from the EXACT regenerated candidate ----------
# Downloads the now-public model + dataset + demo, re-runs geno-lewm-score
# against /carbon, and verifies the replayed demo manifest. Reuse the EXACT
# candidate hub_publish wrote so the chain-of-custody hashes stay identical.
log "clean-machine public replay (downloads live artifacts; re-scores via /carbon)"
REPLAY_DIR="$OUT/clean-machine-public-replay"
HF_HUB_OFFLINE=0 python -m tools.release.clean_machine_demo \
  --release-candidate-report "$CANDIDATE_OUT" \
  --output-dir "$REPLAY_DIR" \
  || fail "clean_machine_demo failed (network download of public artifacts, or Carbon not loadable from $CARBON_DIR during replay)"
CLEAN_REPORT="$REPLAY_DIR/clean_machine_demo_report.json"
test -s "$CLEAN_REPORT" || fail "clean_machine_demo did not write $CLEAN_REPORT"

# --- 8. BIND the publication evidence (the binder) ------------------------
# Cross-checks plan + candidate + publish report + clean-machine replay; exits 0
# iff ok=true. Uses the EXACT candidate bytes from step 6 (chain of custody).
log "bind publication evidence (publication_report; ok=true gate)"
BINDER_OUT="$OUT/publication_evidence_report.json"
python -m tools.release.publication_report \
  --plan "$PLAN_OUT" \
  --release-candidate "$CANDIDATE_OUT" \
  --publish-report "$PUBLISH_OUT" \
  --clean-machine-demo-report "$CLEAN_REPORT" \
  --output "$BINDER_OUT" \
  || fail "publication_report binder failed (exit !=0). Likely a chain-of-custody hash mismatch or a public-readiness regression; inspect $BINDER_OUT"
python - "$BINDER_OUT" <<'PY' || fail "publication_evidence_report.json is not ok"
import json, sys
r = json.load(open(sys.argv[1]))
assert r.get("ok") is True, f"binder ok={r.get('ok')!r}; issues={r.get('issues')}"
print("publication binder ok:", r["ok"])
PY

# --- 9. (optional) bind GitHub asset identities into the release ----------
log "bind GitHub publication asset identities (publication_assets)"
ASSETS_OUT="$OUT/publication_assets_report.json"
ASSETS_ENV_OUT="$OUT/publication_assets.env"
python -m tools.release.publication_assets \
  --demo-url "$DEMO_URL" \
  --hub-release-plan "$PLAN_OUT" \
  --release-candidate "$CANDIDATE_OUT" \
  --publish-report "$PUBLISH_OUT" \
  --clean-machine-demo-report "$CLEAN_REPORT" \
  --publication-report "$BINDER_OUT" \
  --replay-dir "$REPLAY_DIR" \
  --output "$ASSETS_OUT" \
  --env-output "$ASSETS_ENV_OUT" \
  || echo "WARN: publication_assets binding failed (non-fatal); the publication_evidence_report.json binder is already ok"

# --- 10. publish the binder artifacts back to the runs repo ---------------
if [ "$UPLOAD_BINDER" = "1" ]; then
  log "upload binder artifacts to $RUNS_REPO ($BINDER_UPLOAD_SUBPATH)"
  cp -a "$REPLAY_DIR" "$OUT/clean-machine-public-replay" 2>/dev/null || true
  cp "$PAPER_PATH" "$OUT/$PAPER_FILENAME" 2>/dev/null || true
  hf upload "$RUNS_REPO" "$OUT" "$BINDER_UPLOAD_SUBPATH" --repo-type model \
    || echo "WARN: binder upload to $RUNS_REPO failed (binder itself is still ok at $BINDER_OUT)"
  # Also attach the binder JSONs to the GitHub release for public reference.
  gh release upload "$GH_TAG" --repo "$GH_REPO" --clobber \
    "$PLAN_OUT" "$CANDIDATE_OUT" "$PUBLISH_OUT" "$CLEAN_REPORT" "$BINDER_OUT" \
    || echo "WARN: gh release upload of binder JSONs failed (non-fatal)"
fi

echo
echo "GENO_LEWM_PUBLISH_OK $RUN_NAME"
echo "  model    : https://huggingface.co/$REPO_ID"
echo "  dataset  : $DATASET_URL"
echo "  demo     : $DEMO_URL"
echo "  paper    : $PAPER_URL  (AUROC ~0.52, honest near-chance proof)"
echo "  binder   : $BINDER_OUT (ok=true)"
