# SPDX-License-Identifier: Apache-2.0
"""Training helpers for GenoLeWM."""

from geno_lewm.training.collapse import (
    CollapseAlert,
    CollapseCheck,
    CollapseMetrics,
    CollapseMonitor,
    CollapseThresholds,
    compute_collapse_metrics,
    detect_collapse,
    record_collapse_metrics,
)
from geno_lewm.training.fixture import (
    FIXTURE_CHECKPOINT_NAME,
    FIXTURE_DATASET_MANIFEST_NAME,
    FIXTURE_LOG_NAME,
    FIXTURE_METRICS_NAME,
    FIXTURE_TRAINING_METADATA_NAME,
    FixtureTrainingReport,
    run_fixture_training,
)
from geno_lewm.training.preflight import (
    REPORT_NAME,
    REQUIRED_TRAINING_MODULES,
    SCHEMA_VERSION,
    DependencyProbe,
    TrainingPreflightIssue,
    TrainingPreflightReport,
    TrainingPreflightRequest,
    build_training_preflight_report,
    write_training_preflight_report,
)
from geno_lewm.training.real import (
    CARBON_CHECKPOINT_NAME,
    CARBON_LOG_NAME,
    CARBON_METRICS_NAME,
    CARBON_TRAINING_METADATA_NAME,
    CarbonTrainingReport,
    run_carbon_training,
)
from geno_lewm.training.sampling import (
    DEFAULT_EDIT_TYPE_WEIGHTS,
    DEFAULT_ROLLOUT_STEP_MIX,
    EditTypeWeight,
    RolloutStepWeight,
    draw_edit_type_counts,
    draw_rollout_step_counts,
    sample_edit_type,
    sample_rollout_steps,
)
from geno_lewm.training.trainer import (
    TorchDeterminismReport,
    TorchTrainer,
    TorchTrainerBatch,
    TorchTrainerStepResult,
    TrainerSeeds,
    build_adamw_optimizer,
    configure_torch_reproducibility,
    encode_training_batch,
    make_action_mask,
    set_optimizer_lr,
    wsd_lr_multiplier,
)

__all__ = [
    "CARBON_CHECKPOINT_NAME",
    "CARBON_LOG_NAME",
    "CARBON_METRICS_NAME",
    "CARBON_TRAINING_METADATA_NAME",
    "DEFAULT_EDIT_TYPE_WEIGHTS",
    "DEFAULT_ROLLOUT_STEP_MIX",
    "FIXTURE_CHECKPOINT_NAME",
    "FIXTURE_DATASET_MANIFEST_NAME",
    "FIXTURE_LOG_NAME",
    "FIXTURE_METRICS_NAME",
    "FIXTURE_TRAINING_METADATA_NAME",
    "REPORT_NAME",
    "REQUIRED_TRAINING_MODULES",
    "SCHEMA_VERSION",
    "CarbonTrainingReport",
    "CollapseAlert",
    "CollapseCheck",
    "CollapseMetrics",
    "CollapseMonitor",
    "CollapseThresholds",
    "DependencyProbe",
    "EditTypeWeight",
    "FixtureTrainingReport",
    "RolloutStepWeight",
    "TorchDeterminismReport",
    "TorchTrainer",
    "TorchTrainerBatch",
    "TorchTrainerStepResult",
    "TrainerSeeds",
    "TrainingPreflightIssue",
    "TrainingPreflightReport",
    "TrainingPreflightRequest",
    "build_adamw_optimizer",
    "build_training_preflight_report",
    "compute_collapse_metrics",
    "configure_torch_reproducibility",
    "detect_collapse",
    "draw_edit_type_counts",
    "draw_rollout_step_counts",
    "encode_training_batch",
    "make_action_mask",
    "record_collapse_metrics",
    "run_carbon_training",
    "run_fixture_training",
    "sample_edit_type",
    "sample_rollout_steps",
    "set_optimizer_lr",
    "write_training_preflight_report",
    "wsd_lr_multiplier",
]
