"""Tests for the v0.2 serious-completion paper package."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from geno_lewm.errors import InputError
from geno_lewm.provenance import sha256_bytes, sha256_file
from tools.release.eval_report import parse_report_input, render_report
from tools.release.paper_draft import main as paper_draft_main
from tools.release.paper_package import main as paper_package_main
from tools.release.serious_completion_paper import (
    SeriousCompletionPaperPaths,
    build_serious_completion_paper,
    verify_serious_completion_paper,
)

MODEL_ID = sha256_bytes(b"serious-completion-model-manifest")
MODEL_RELEASE = "geno-lewm-v0.2.1-r1"
DATASET_SNAPSHOT = "geno-lewm-data-v0.2.1-r1"
COMMIT = "d9b06815cf8e64860f51d236b8db6ba55aa4154d"
HARDWARE = "local evidence host"


def test_build_serious_completion_paper_binds_artifact_identities(tmp_path: Path) -> None:
    suite_dir, planning_dir = _write_serious_completion_inputs(tmp_path)
    output = tmp_path / "paper.serious.md"

    report = build_serious_completion_paper(
        suite_dir=suite_dir,
        planning_demo_dir=planning_dir,
        output=output,
        generated_at="2026-06-09T03:00:00Z",
    )
    text = output.read_text(encoding="utf-8")

    assert report.model_id == MODEL_ID
    assert report.model_release == MODEL_RELEASE
    assert report.dataset_snapshot == DATASET_SNAPSHOT
    assert "Generated by: tools.release.paper_draft" in text
    assert "Paper kind: serious_completion_v0.2" in text
    assert "## Introduction" in text
    assert "## Related Work" in text
    assert "## Method" in text
    assert "## Experiments" in text
    assert "## Citation Metadata" in text
    assert "## Artifact Inputs" in text
    assert "## Planning Demo Evidence" in text
    assert "## Discussion and Learnings" in text
    assert "## Negative Findings" in text
    assert "## Reproducibility" in text
    assert "## References" in text
    assert "DNABERT" in text
    assert "HyenaDNA" in text
    assert "Nucleotide Transformer" in text
    assert "AlphaMissense" in text
    assert "negative-results and systems" in text
    assert "K20" in text
    assert "does not prove useful planning behavior" in text
    assert "`23.656930390534644`" in text
    assert "v0.2_benchmark_readiness_report.json" in text
    assert "planning_demo_manifest.json" in text
    assert str(tmp_path) not in text


def test_paper_package_serious_completion_accepts_generated_paper(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    suite_dir, planning_dir = _write_serious_completion_inputs(tmp_path)
    output = tmp_path / "paper.serious.md"
    build_serious_completion_paper(
        suite_dir=suite_dir,
        planning_demo_dir=planning_dir,
        output=output,
        generated_at="2026-06-09T03:00:00Z",
    )

    report = verify_serious_completion_paper(
        SeriousCompletionPaperPaths(
            suite_dir=suite_dir,
            planning_demo_dir=planning_dir,
            paper_path=output,
        )
    )
    rc = paper_package_main(
        [
            "--serious-completion",
            "--suite-dir",
            str(suite_dir),
            "--planning-demo-dir",
            str(planning_dir),
            "--paper-path",
            str(output),
        ]
    )
    captured = capsys.readouterr()

    assert report.ok is True
    assert rc == 0
    payload = json.loads(captured.out)
    assert payload["ok"] is True
    assert payload["model_id"] == MODEL_ID


def test_paper_draft_main_serious_completion_outputs_json_report(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    suite_dir, planning_dir = _write_serious_completion_inputs(tmp_path)
    output = tmp_path / "paper.serious.md"

    rc = paper_draft_main(
        [
            "--serious-completion",
            "--suite-dir",
            str(suite_dir),
            "--planning-demo-dir",
            str(planning_dir),
            "--output",
            str(output),
        ]
    )
    captured = capsys.readouterr()

    assert rc == 0
    payload = json.loads(captured.out)
    assert payload["path"] == "paper.serious.md"
    assert payload["model_id"] == MODEL_ID
    assert payload["readiness_report"] == "suite/model/v0.2_benchmark_readiness_report.json"
    assert payload["planning_manifest"] == "planning-demo/planning_demo_manifest.json"


def test_serious_completion_verifier_rejects_stale_generated_paper(tmp_path: Path) -> None:
    suite_dir, planning_dir = _write_serious_completion_inputs(tmp_path)
    output = tmp_path / "paper.serious.md"
    build_serious_completion_paper(
        suite_dir=suite_dir,
        planning_demo_dir=planning_dir,
        output=output,
        generated_at="2026-06-09T03:00:00Z",
    )
    output.write_text(
        output.read_text(encoding="utf-8").replace(
            "negative-results and systems",
            "improved-results and systems",
        ),
        encoding="utf-8",
    )

    report = verify_serious_completion_paper(
        SeriousCompletionPaperPaths(
            suite_dir=suite_dir,
            planning_demo_dir=planning_dir,
            paper_path=output,
        )
    )

    assert report.ok is False
    assert "serious_paper.negative_results" in _codes(report)
    assert "serious_paper.stale" in _codes(report)


def test_serious_completion_build_rejects_stale_planning_manifest_identity(
    tmp_path: Path,
) -> None:
    suite_dir, planning_dir = _write_serious_completion_inputs(tmp_path)
    (planning_dir / "source_window.fa").write_text(">13\nACGT\n", encoding="utf-8")

    with pytest.raises(InputError, match="artifact identity is stale"):
        build_serious_completion_paper(
            suite_dir=suite_dir,
            planning_demo_dir=planning_dir,
            output=tmp_path / "paper.serious.md",
        )


def _codes(report) -> set[str]:
    return {issue.code for issue in report.issues}


def _write_serious_completion_inputs(root: Path) -> tuple[Path, Path]:
    suite_dir = root / "suite"
    model_dir = suite_dir / "model"
    bench_dir = suite_dir / "bench"
    planning_dir = root / "planning-demo"
    model_dir.mkdir(parents=True)
    bench_dir.mkdir(parents=True)
    planning_dir.mkdir()

    metrics_payload = _eval_metrics_payload()
    metrics_path = model_dir / "eval_metrics.v02.json"
    metrics_path.write_text(
        json.dumps(metrics_payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    report = render_report(parse_report_input(metrics_payload))
    (model_dir / "eval_report.v02.md").write_text(report, encoding="utf-8")
    (model_dir / "efficiency_report.v02.json").write_text(
        json.dumps(_efficiency_payload(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (model_dir / "v0.2_benchmark_suite_report.json").write_text(
        json.dumps(_suite_report_payload(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (bench_dir / "rollout.ar_speed.json").write_text(
        json.dumps(_rollout_speed_payload(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (bench_dir / "rollout_speed_scope.json").write_text(
        json.dumps(
            _rollout_speed_scope_payload(bench_dir / "rollout.ar_speed.json"),
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    (model_dir / "v0.2_benchmark_readiness_report.json").write_text(
        json.dumps(_readiness_payload(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    _write_planning_artifacts(planning_dir)
    return suite_dir, planning_dir


def _eval_metrics_payload() -> dict[str, object]:
    key_hash = sha256_bytes(b"variant keys")
    return {
        "schema_version": "1.0.0",
        "generated_by": "geno-lewm-eval-all",
        "generated_at": "2026-06-09T02:00:00Z",
        "model_id": MODEL_ID,
        "model_release": MODEL_RELEASE,
        "dataset_snapshot": DATASET_SNAPSHOT,
        "commit": COMMIT,
        "hardware": HARDWARE,
        "metrics": [
            {
                "name": "auroc",
                "split": "clinvar_coding",
                "value": 0.7,
                "unit": "area",
                "higher_is_better": True,
                "baseline": "carbon_zero_shot",
                "baseline_value": 0.9,
                "delta_vs_baseline": -0.2,
                "ci_low": 0.6,
                "ci_high": 0.8,
                "n": 16,
                "notes": "measured row",
                "evaluated_variant_keys_sha256": key_hash,
                "baseline_evaluated_variant_keys_sha256": key_hash,
            }
        ],
        "artifacts": {
            "checkpoint": "model/predictor.safetensors",
            "config": "model/training_config.effective.yaml",
            "dataset_manifest": "dataset/dataset_manifest.json",
            "efficiency_report": "model/efficiency_report.v02.json",
            "eval_config": "eval_config.effective.yaml",
            "input_1.baseline_scores": "eval/clinvar_coding.carbon_zero_shot_scores.jsonl",
            "input_1.labels": "eval/clinvar_coding.labels.jsonl",
            "input_1.scores": "eval/clinvar_coding.scores.jsonl",
        },
        "limitations": ["The row is bounded to this evidence package."],
        "negative_findings": ["No broad model-quality claim is established."],
        "conclusions": [
            "The auroc metric on clinvar_coding measured 0.7 against carbon_zero_shot "
            "with baseline delta -0.2."
        ],
    }


def _efficiency_payload() -> dict[str, object]:
    return {
        "schema_version": "1.0.0",
        "generated_by": "tools.release.efficiency_report",
        "generated_at": "2026-06-09T02:01:00Z",
        "model_id": MODEL_ID,
        "model_release": MODEL_RELEASE,
        "dataset_snapshot": DATASET_SNAPSHOT,
        "commit": COMMIT,
        "command": ["python", "-m", "bench.inference", "--release-efficiency"],
        "hardware": HARDWARE,
        "runtime": "cpu",
        "warmup_batches": 1,
        "samples": 2,
        "measurements": {
            "single_variant_latency_ms": 115262.939968,
            "batched_throughput_variants_per_s": 0.3095340544239052,
            "peak_memory_bytes": 1966149632,
        },
        "inputs": {
            "vcf": {
                "path": "eval/clinvar_coding.vcf",
                "sha256": sha256_bytes(b"vcf"),
                "size_bytes": 12,
            }
        },
        "limitations": ["Measured on a bounded evidence host."],
    }


def _suite_report_payload() -> dict[str, object]:
    return {
        "schema_version": "1.0.0",
        "generated_by": "tools.release.v02_benchmark_suite",
        "generated_at": "2026-06-09T02:02:00Z",
        "ok": True,
        "status": "pass",
        "manifest_path": "v0.2_benchmark_suite.template.json",
        "manifest": {
            "path": "v0.2_benchmark_suite.template.json",
            "sha256": sha256_bytes(b"manifest"),
            "size_bytes": 3,
        },
        "execute": True,
        "steps": [{"id": "aggregate.eval_all", "kind": "aggregate_eval", "status": "pass"}],
        "negative_findings": ["Measured claims depend on downstream artifact validators."],
        "claim_boundary": "This suite is not clinical, privacy, runtime, or model-quality evidence by itself.",
    }


def _readiness_payload() -> dict[str, object]:
    rows = [
        _benchmark_row(
            "clinvar_coding",
            "pass",
            {"auroc": 0.734375, "balanced_accuracy": 0.75, "accuracy": 0.75},
            {"auroc": -0.1875, "balanced_accuracy": 0.0625, "accuracy": 0.0625},
        ),
        _benchmark_row(
            "clinvar_noncoding",
            "pass",
            {"auroc": 0.5625},
            {"auroc": -0.3125},
        ),
        _benchmark_row(
            "brca2_saturation",
            "pass",
            {"spearman_rho": 0.14919354838709678},
            {"spearman_rho": -0.32771260997067453},
        ),
        _benchmark_row(
            "traitgym_mendelian",
            "pass",
            {"spearman_rho": -0.02796450759873114},
            {"spearman_rho": 0.05592901519746229},
        ),
        _benchmark_row(
            "rollout_phased_haplotypes",
            "pass",
            {"cosine_similarity_mean": 0.28886058350550603, "l2_distance_mean": 33.319687258878126},
            {"cosine_similarity_mean": -0.7089701215468133, "l2_distance_mean": 31.19289051130368},
        ),
        _benchmark_row(
            "rollout_synthetic_edit_chains",
            "pass",
            {"cosine_similarity_mean": 0.30160847029349436, "l2_distance_mean": 28.802888778495763},
            {"cosine_similarity_mean": -0.6896310938123016, "l2_distance_mean": 25.637059814259455},
        ),
        {
            "benchmark_id": "inference_efficiency",
            "status": "pass",
            "observed_values": {
                "single_variant_latency_ms": 115262.939968,
                "batched_throughput_variants_per_s": 0.3095340544239052,
                "peak_memory_bytes": 1966149632,
            },
            "issue_refs": ["#56", "#58", "#197"],
        },
        {
            "benchmark_id": "ar_rollout_speed",
            "status": "rescoped",
            "observed_values": {"k5_speedup": 2.413859489667916, "k20_speedup": 2.4732225135799566},
            "scope_decision": {"status": "accepted", "decision": "rescope_rfc0004_speed_target"},
            "issue_refs": ["#42", "#197"],
        },
        {"benchmark_id": "release_inputs", "status": "pass", "issue_refs": ["#197"]},
    ]
    return {
        "schema_version": "1.0.0",
        "generated_by": "tools.release.v02_benchmark_readiness",
        "generated_at": "2026-06-09T02:03:00Z",
        "ok": True,
        "model_id": MODEL_ID,
        "model_release": MODEL_RELEASE,
        "dataset_snapshot": DATASET_SNAPSHOT,
        "commit": COMMIT,
        "hardware": HARDWARE,
        "release_inputs_required": True,
        "benchmark_rows": rows,
        "missing_or_failed_benchmarks": [],
        "negative_findings": [
            "No clinical utility, privacy, runtime assurance, or deployment claim is established."
        ],
        "claim_boundary": "This report is not clinical, privacy, runtime, or model-quality evidence beyond measured inputs.",
    }


def _benchmark_row(
    benchmark_id: str,
    status: str,
    observed: dict[str, float],
    delta: dict[str, float],
) -> dict[str, object]:
    return {
        "benchmark_id": benchmark_id,
        "status": status,
        "observed_values": observed,
        "delta_vs_baseline": delta,
        "issue_refs": ["#197"],
    }


def _rollout_speed_payload() -> dict[str, object]:
    return {
        "schema_version": "1.0.0",
        "generated_by": "bench.rollout",
        "generated_at": "2026-06-09T02:04:00Z",
        "ok": False,
        "commit": COMMIT,
        "command": ["python", "-m", "bench.rollout"],
        "rows": [
            {
                "horizon": 5,
                "measured_speedup": 2.413859489667916,
                "target_speedup": 2.0,
                "target_met": True,
            },
            {
                "horizon": 20,
                "measured_speedup": 2.4732225135799566,
                "target_speedup": 5.0,
                "target_met": False,
            },
        ],
        "claim_boundary": "This benchmark is not clinical, privacy, runtime, or model-quality evidence.",
    }


def _rollout_speed_scope_payload(rollout_path: Path) -> dict[str, object]:
    return {
        "schema_version": "1.0.0",
        "generated_by": "tools.release.rollout_speed_scope",
        "generated_at": "2026-06-09T02:05:00Z",
        "ok": True,
        "status": "accepted",
        "decision": "rescope_rfc0004_speed_target",
        "issue_refs": ["#42", "#197"],
        "rollout_speed_report": {
            "path": "bench/rollout.ar_speed.json",
            "sha256": sha256_file(rollout_path),
            "size_bytes": rollout_path.stat().st_size,
        },
        "negative_findings": ["The RFC-0004 K20 target was not met."],
        "claim_boundary": "This report is not clinical, privacy, runtime, or model-quality evidence.",
    }


def _write_planning_artifacts(planning_dir: Path) -> None:
    (planning_dir / "source_window.fa").write_text(">13\n" + "A" * 32 + "\n", encoding="utf-8")
    (planning_dir / "target_window.fa").write_text(">13\n" + "C" * 32 + "\n", encoding="utf-8")
    target_edits = [
        {"chrom": "13", "pos": 32356096, "rel_pos": 4096, "ref": "G", "alt": "A"},
        {"chrom": "13", "pos": 32358144, "rel_pos": 6144, "ref": "C", "alt": "A"},
    ]
    (planning_dir / "target_edits.json").write_text(
        json.dumps(target_edits, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    summary = {
        "evaluation_mode": "manifest_runtime",
        "model_id": MODEL_ID,
        "best_distance": 23.656930390534644,
        "best_objective": 23.656930390534644,
        "n_evaluations": 384,
        "elapsed_seconds": 15.341928750043735,
        "stopped_reason": "patience",
        "best_edits": [
            {"rel_pos": 2515, "ref_bases": "C", "alt_bases": "G", "edit_type": "SNV"},
            {"rel_pos": 8439, "ref_bases": "A", "alt_bases": "G", "edit_type": "SNV"},
        ],
    }
    plan = {
        "schema_version": "0.1",
        "generated_by": "geno-lewm-plan",
        "evaluation_mode": "manifest_runtime",
        "runtime": {"model_id": MODEL_ID, "backend": "auto"},
        "result": {
            key: value
            for key, value in summary.items()
            if key not in {"evaluation_mode", "model_id"}
        },
        "negative_findings": [],
        "claim_boundary": "Planning output is not clinical, privacy-assurance, or runtime-assurance evidence.",
    }
    (planning_dir / "plan.json").write_text(
        json.dumps(plan, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (planning_dir / "plan.stdout.json").write_text('{"ok": true}\n', encoding="utf-8")
    (planning_dir / "planning-demo-transcript.md").write_text(
        "# GenoLeWM Planning Demo\n\n"
        "Generated: 2026-06-09T02:06:00Z\n\n"
        "## Result\n\n"
        "- best_distance: 23.656930390534644\n"
        "- stopped_reason: patience\n",
        encoding="utf-8",
    )
    manifest = {
        "schema_version": "1.0.0",
        "generated_by": "tools.jobs.planning_demo_run",
        "generated_at": "2026-06-09T02:07:00Z",
        "status": "passed",
        "command": {"argv": ["geno-lewm-plan", "--output", "demo/plan.json"]},
        "plan_summary": summary,
        "artifacts": _planning_manifest_artifacts(planning_dir),
        "negative_findings": [
            "The demo records one deterministic synthetic target and does not prove useful planning behavior."
        ],
        "claim_boundary": (
            "This planning demo is not clinical, deployment readiness, privacy assurance, "
            "runtime assurance, or useful planning behavior evidence."
        ),
    }
    (planning_dir / "planning_demo_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _planning_manifest_artifacts(planning_dir: Path) -> dict[str, object]:
    artifacts: dict[str, object] = {
        "model_manifest": {"path": "model/manifest.json", "sha256": MODEL_ID, "size_bytes": 1085},
        "predictor": {
            "path": "model/predictor.safetensors",
            "sha256": sha256_bytes(b"predictor"),
            "size_bytes": 122446936,
        },
        "action_encoder": {
            "path": "model/action_encoder.safetensors",
            "sha256": sha256_bytes(b"action_encoder"),
            "size_bytes": 8559712,
        },
    }
    for label, name in {
        "source_window": "source_window.fa",
        "target_window": "target_window.fa",
        "target_edits": "target_edits.json",
        "plan": "plan.json",
        "plan_stdout": "plan.stdout.json",
        "transcript": "planning-demo-transcript.md",
    }.items():
        path = planning_dir / name
        artifacts[label] = {
            "path": f"demo/{name}",
            "sha256": sha256_file(path),
            "size_bytes": path.stat().st_size,
        }
    return artifacts
