"""Tests for the generated first-experiment paper draft."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from geno_lewm.errors import InputError
from tests.unit.test_release_paper_package import _write_complete_package
from tools.release.paper_draft import build_paper_draft, main


def test_build_paper_draft_uses_release_artifact_identity(tmp_path: Path) -> None:
    paths = _write_complete_package(tmp_path)
    output = tmp_path / "generated-paper.md"

    report = build_paper_draft(
        model_dir=paths.model_dir,
        dataset_dir=paths.dataset_dir,
        demo_dir=paths.demo_dir,
        output=output,
        generated_at="2026-06-01T12:00:00Z",
    )
    text = output.read_text(encoding="utf-8")

    assert report.model_id in text
    assert report.dataset_snapshot in text
    assert "Generated by: tools.release.paper_draft" in text
    assert "## Citation Metadata" in text
    assert f"- Model id: `{report.model_id}`" in text
    assert f"- Dataset snapshot: `{report.dataset_snapshot}`" in text
    assert "## Results" in text
    assert "## Conclusions" in text
    assert "## Negative Findings" in text
    assert "## Limitations" in text
    assert "## Artifact Availability" in text
    assert str(tmp_path) not in text
    assert "Model directory:" not in text
    assert "Dataset directory:" not in text
    assert "Demo directory:" not in text
    assert "- Model package root: model release package" in text
    assert "- Dataset package root: dataset release package" in text
    assert "- Demo package root: terminal demo package" in text
    assert "model_package.json" in text
    assert "dataset_package.json" in text
    assert "dataset_input_check_report.json" in text
    assert "dataset_snapshot_report.json" in text
    assert "eval_metrics.json" in text
    assert "eval_config.effective.yaml" in text
    assert "eval_report.md" in text
    assert "terminal-demo-transcript.md" in text
    assert "terminal_demo_manifest.json" in text
    assert "runtime_preflight_report.json" in text
    assert "batch_receipt_report.json" in text
    assert "The packaged demo VCF contains 1 variant record(s), 1 alternate allele(s)" in text
    assert "First demo variant(s): 1:10:A>T." in text
    assert "No clinical utility claim is measured by this fixture report." in text


def test_paper_draft_main_outputs_json_report(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    paths = _write_complete_package(tmp_path)
    output = tmp_path / "paper.md"

    rc = main(
        [
            "--model-dir",
            str(paths.model_dir),
            "--dataset-dir",
            str(paths.dataset_dir),
            "--demo-dir",
            str(paths.demo_dir),
            "--output",
            str(output),
        ]
    )
    captured = capsys.readouterr()

    assert rc == 0
    payload = json.loads(captured.out)
    assert str(tmp_path) not in json.dumps(payload)
    assert payload["path"] == "paper.md"
    assert payload["model_id"].startswith("sha256:")
    assert payload["model_package"] == "model/model_package.json"
    assert payload["dataset_input_check_report"] == "dataset/dataset_input_check_report.json"
    assert payload["dataset_snapshot_report"] == "dataset/dataset_snapshot_report.json"
    assert payload["efficiency_report"] == "model/efficiency_report.json"
    assert payload["demo_transcript"] == "demo/terminal-demo-transcript.md"
    assert payload["demo_manifest"] == "demo/terminal_demo_manifest.json"
    assert payload["runtime_preflight_report"] == "demo/runtime_preflight_report.json"
    assert payload["batch_receipt_report"] == "demo/batch_receipt_report.json"


def test_build_paper_draft_requires_dataset_snapshot_report(tmp_path: Path) -> None:
    paths = _write_complete_package(tmp_path)
    (paths.dataset_dir / "dataset_snapshot_report.json").unlink()

    with pytest.raises(InputError, match="dataset snapshot report"):
        build_paper_draft(
            model_dir=paths.model_dir,
            dataset_dir=paths.dataset_dir,
            demo_dir=paths.demo_dir,
            output=tmp_path / "paper.md",
        )


def test_build_paper_draft_requires_dataset_input_check_report(tmp_path: Path) -> None:
    paths = _write_complete_package(tmp_path)
    (paths.dataset_dir / "dataset_input_check_report.json").unlink()

    with pytest.raises(InputError, match="dataset input-check report"):
        build_paper_draft(
            model_dir=paths.model_dir,
            dataset_dir=paths.dataset_dir,
            demo_dir=paths.demo_dir,
            output=tmp_path / "paper.md",
        )


def test_build_paper_draft_rejects_placeholder_generated_text(tmp_path: Path) -> None:
    paths = _write_complete_package(tmp_path)
    package_path = paths.model_dir / "training_run_manifest.json"
    payload = json.loads(package_path.read_text(encoding="utf-8"))
    payload["command"] = "TODO"
    package_path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    with pytest.raises(InputError, match="placeholder text"):
        build_paper_draft(
            model_dir=paths.model_dir,
            dataset_dir=paths.dataset_dir,
            demo_dir=paths.demo_dir,
            output=tmp_path / "paper.md",
        )


def test_build_paper_draft_requires_utc_generated_timestamp(tmp_path: Path) -> None:
    paths = _write_complete_package(tmp_path)

    with pytest.raises(InputError, match="UTC ISO-8601"):
        build_paper_draft(
            model_dir=paths.model_dir,
            dataset_dir=paths.dataset_dir,
            demo_dir=paths.demo_dir,
            output=tmp_path / "paper.md",
            generated_at="June 1, 2026",
        )


def test_build_paper_draft_rejects_stale_eval_report(tmp_path: Path) -> None:
    paths = _write_complete_package(tmp_path)
    report_path = paths.model_dir / "eval_report.md"
    report_path.write_text(
        report_path.read_text(encoding="utf-8").replace(
            "The auroc metric value 0.73",
            "The result was measured",
        ),
        encoding="utf-8",
    )

    with pytest.raises(InputError, match="does not match render"):
        build_paper_draft(
            model_dir=paths.model_dir,
            dataset_dir=paths.dataset_dir,
            demo_dir=paths.demo_dir,
            output=tmp_path / "paper.md",
        )


def test_build_paper_draft_rejects_stale_demo_vcf_summary(tmp_path: Path) -> None:
    paths = _write_complete_package(tmp_path)
    manifest_path = paths.demo_dir / "terminal_demo_manifest.json"
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    payload["inputs"]["vcf_summary"]["alternate_alleles"] = 2
    manifest_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")

    with pytest.raises(InputError, match="vcf_summary does not match"):
        build_paper_draft(
            model_dir=paths.model_dir,
            dataset_dir=paths.dataset_dir,
            demo_dir=paths.demo_dir,
            output=tmp_path / "paper.md",
        )


def test_build_paper_draft_requires_eval_config_artifact(tmp_path: Path) -> None:
    paths = _write_complete_package(tmp_path)
    metrics_path = paths.model_dir / "eval_metrics.json"
    payload = json.loads(metrics_path.read_text(encoding="utf-8"))
    del payload["artifacts"]["eval_config"]
    metrics_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")

    with pytest.raises(InputError, match="required keys"):
        build_paper_draft(
            model_dir=paths.model_dir,
            dataset_dir=paths.dataset_dir,
            demo_dir=paths.demo_dir,
            output=tmp_path / "paper.md",
        )
